table 'Pack visual table'
	lineageTag: 2761e5be-3980-4b2d-8f2e-a2756a20c3ea

	column QUARTER
		dataType: string
		lineageTag: a55b0617-d1fb-46b5-a23d-1443eec1fe09
		summarizeBy: none
		sourceColumn: QUARTER
		sortByColumn: 'sort for quater'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Metrics
		dataType: string
		lineageTag: 3c8784c6-6846-48c6-93b4-5ef3c63a2cc5
		summarizeBy: none
		sourceColumn: Metrics
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: d567a3c6-2032-4ed2-b674-ec371c841e4d
		summarizeBy: sum
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	column 'sort for quater'
		dataType: int64
		formatString: 0
		lineageTag: 83962e3f-fb35-4d91-a78e-2997bac06888
		summarizeBy: sum
		sourceColumn: sort for quater

		annotation SummarizationSetBy = Automatic

	partition 'Pack visual table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCjQ0MlXSUQrLzynNTQUyDIHYRClWByhjYmQC5ECQMUTIGEnICCJkBNYPQaYwIYQqQ5hGhCoziBDEYlUFuNVGdLE6FgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [QUARTER = _t, Metrics = _t, Sort = _t, #"sort for quater" = _t]),
				    #"Changed Type2" = Table.TransformColumnTypes(Source,{{"sort for quater", Int64.Type}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type2",{{"QUARTER", type text}, {"Metrics", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","",null,Replacer.ReplaceValue,{"Metrics"}),
				    #"Filled Down" = Table.FillDown(#"Replaced Value",{"Metrics"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Filled Down","",null,Replacer.ReplaceValue,{"Sort"}),
				    #"Filled Down1" = Table.FillDown(#"Replaced Value1",{"Sort"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Filled Down1",{{"Sort", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

